version: "2"
services:
    nagios4:
        image: jasonrivers/nagios:latest
        container_name: nagios4
        ports:
            - 8080:80
        volumes:
            - /vagrant/src:/opt/nagios/share/Merc
            - /vagrant/plugins/vshell:/opt/Custom-Nagios-Plugins/vshell 
